### ISSUE TITLE
Can't move .html file without breaking

### ISSUE THREAD

**Issue by Glovba** [jeertmans/manim-slides#104]

**Comment by Glovba** [comment]
I figured it out. I was trying to transport the .html to a USB so I can present it, I'm a High School Math teacher. I had to copy the assets over to the USB as well, then everything worked.

Thanks for a great program!

**Comment by jeertmans** [comment]
Hi @Glovba, I am happy you found a solution!
Indeed, one needs to move the assets too. Maybe that should be documented somewhere…

If you encounter any other issue regarding portability, please reach out to me :)
