### ISSUE TITLE
[FEATURE] Manim Web support

### ISSUE THREAD

**Issue by Wizorx** [jeertmans/manim-slides#107]
### Description

So, there's this version of manim that allows you to create interactive diagrams, is there (or could there be in the future) a way to embed one of those inside a slide? [Here's](https://manim-web.hugos29.dev/) the site and some examples of diagrams I made that I'd like to embed into a slide:
- [Linear Alebra Stuff](https://wizorx.github.io/AstroWidgets/AlgLin/playground.html)
- [Derivative](https://wizorx.github.io/AstroWidgets/AlgLin/derivative.html)
- [Integrals](https://wizorx.github.io/AstroWidgets/AlgLin/integrals.html)

P.S.: forgot to mention that the exports of manim web can also be .html files with an .js script, maybe that will ease things up

**Comment by jeertmans** [comment]
Hi @Wizorx! So I didn't know about manim web until now, but it seems to be a great tool!

If it creates HTML files, then it should be very easy to include them with Manim Slides.

However, is it a true "wrapper" around the Manim library, or does it re-implement just most of what Manim does, but when Dart.js.
I am a bit worried about how to integrate it with the actual library, which is written in Python. 

If you know more about manim web, please tell me!

Currently, I suggest you to modify the HTML template and add `iframe` slides manually: https://revealjs.com/backgrounds/#iframe-backgrounds.

**Comment by Wizorx** [comment]
Unfortunately I don't know much about it, no. But I'm sure if you hit Hugo up on discord he'll for sure help you out. And thanks for the iframe tip!
