### ISSUE TITLE
[BUG] can't run manim-slides on ubuntu (from within conda environments)

### ISSUE THREAD

**Issue by AlexanderTyan** [jeertmans/manim-slides#109]
### Description

After following the installation steps, running `manim-slides` in a command line (oh-my-zsh) yields:
```
Traceback (most recent call last):
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manimpango/__init__.py", line 14, in <module>
    from .cmanimpango import *  # noqa: F403,F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manimpango/../../../libgobject-2.0.so.0: undefined symbol: g_uri_ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/incognito/anaconda3/envs/manim-slides/bin/manim-slides", line 5, in <module>
    from manim_slides.__main__ import cli
  File "/home/incognito/Repositories/manim-slides/manim_slides/__init__.py", line 3, in <module>
    from .slide import Slide, ThreeDSlide
  File "/home/incognito/Repositories/manim-slides/manim_slides/slide.py", line 9, in <module>
    from .config import PresentationConfig, SlideConfig, SlideType
  File "/home/incognito/Repositories/manim-slides/manim_slides/config.py", line 11, in <module>
    from .manim import FFMPEG_BIN, logger
  File "/home/incognito/Repositories/manim-slides/manim_slides/manim.py", line 76, in <module>
    from manim import Scene, ThreeDScene, config, logger
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manim/__init__.py", line 32, in <module>
    from .animation.numbers import *
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manim/animation/numbers.py", line 10, in <module>
    from manim.mobject.text.numbers import DecimalNumber
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manim/mobject/text/numbers.py", line 15, in <module>
    from manim.mobject.text.text_mobject import Text
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manim/mobject/text/text_mobject.py", line 64, in <module>
    import manimpango
  File "/home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manimpango/__init__.py", line 35, in <module>
    raise ImportError(msg)
ImportError: 

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

    * ManimPango v0.4.3, Python v3.11.0

If you believe there is a greater problem,
feel free to contact us or create an issue on GitHub:

    * Discord: https://www.manim.community/discord/
    * GitHub: https://github.com/ManimCommunity/ManimPango/issues

Original error: /home/incognito/anaconda3/envs/manim-slides/lib/python3.11/site-packages/manimpango/../../../libgobject-2.0.so.0: undefined symbol: g_uri_ref
```

Activating `python` and doing `import manimpango` works fine though. Not sure what the issue is.

### Version

`manim-slides --version` gives that same error ^ and stacktrace.

### Platform

`lsb_release -a` gives:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by AlexanderTyan** [comment]
I've also tried:
```
sudo apt-get update
sudo apt-get install libglib2.0-0
```
and still get the same error

**Comment by jeertmans** [comment]
Hi @AlexanderTyan, thanks for reaching me about this issue!
I think this is related to a bad Manim install, and especially to virtual environments.

Correct me if I am wrong: you are using Manim community and installed within a Conda environnement?

If yes, did you follow the instruction guidelines provided here: https://docs.manim.community/en/stable/installation.html?

If Manim works, but Manim Slides not, I think you installed both packages in two separate environnements.

I do not use conda, and everything worked as expected using the usual Pip-way 
: https://docs.manim.community/en/stable/installation/linux.html.

**Comment by AlexanderTyan** [comment]
>  you are using Manim community and installed within a Conda environnement?  
Yes. I have followed the official Manim guide to installing to conda environments though.

> If Manim works, but Manim Slides not, I think you installed both packages in two separate environnements.
Yes, Manim works, just not the `manim-slides`. I've tried pip installing manim as well, but still within conda environments. Maybe I need to try a different virtual env tool. I just don't want to keep a clean separation between python environment I have.

Thanks for your help and the package!

**Comment by jeertmans** [comment]
I don’t think Pyside6 can be installed within a conda environnement, at least not directly.
I understand that keeping your Python envs clean is important to you! But you should totally be able to have a working installation with other virtual env manager.

About conda, can you share here the output of installing Manim Slides within a new conda environment?

**Comment by 51616** [comment]
`conda install -c anaconda glib` works for me.
