### ISSUE TITLE
[FEATURE] manim-slides jupyter magic

### ISSUE THREAD

**Issue by dmadisetti** [jeertmans/manim-slides#122]
### Description

Super cool project, thanks for doing this.

I'd love to be able to run this seamlessly in a Jupyter notebook. It's almost there, looks like a simple magic could do the trick. What do you think?

In the example below, we have:
```
%%manim -qm -v WARNING BasicExample
```
as the magic, so for the magic, I'd expect we'd want syntax like
```
%%manim-slides BasicExample
```

Which should read in the script and return an HTML IPython object with the revealjs page

### Screenshots

ici voila

![Screenshot Capture - 2023-02-07 - 13-40-00](https://user-images.githubusercontent.com/2689338/217336044-8059e192-3e63-45b6-a3c1-96c40dc6c71e.png)

### Additional information

Here's the notebook: https://colab.research.google.com/drive/1K2EVdySR7H5DtLstFtX8h2mvtSW7af6O?usp=sharing

**Comment by jeertmans** [comment]
Hi, thanks and good idea! I guess it would be better to use Manim-slides convert for HTML output since its in HTML.

Do you know anything about Jupyter magicks? I have never written one before

**Comment by dmadisetti** [comment]
You can think of the magic as a decorator for the block, and the contents as a string

Simple/Naive way is write the contents to a temp file, and then execute as normal. A returned IPython object will render in special way, so that's this: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.HTML

It looks like the Manim way evaluates the code, and then passes on everything to `main`, which is the most correct was of doing things. Output is written to temp file and then rendered: they make a [Video](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Video) or Image object and [display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display) it: https://github.com/ManimCommunity/manim/blob/bd844f46d804c8cad50d06ad20ab5bebaee9987b/manim/utils/ipython_magic.py#L185

**Comment by dmadisetti** [comment]
I looked at this a tiny bit more, 2 maybe 3 code changes are required in addition to just the magic:

- [ ] Decouple convert from click (or make new fn). Ideally we just want to call from the magic:
```python
from manim_slides import convert
convert(["BasicExample"], "SrcFolder", "DestFolder")
```

- [ ] Flip the embedded flag for reveal: https://github.com/jeertmans/manim-slides/blob/c0c73ad4d4771bd3593ca503cca21aedab31f7b3/manim_slides/data/revealjs_template.html#L168 There maybe be a few other flags that will be required to make things look right


- [ ] Most important (for google colab at least), the video has to be encoded as a data URI, as the file system is not accessible so this: https://github.com/jeertmans/manim-slides/blob/9cb1c35f00c67b6c839e953d7ac492a860abec7a/manim_slides/convert.py#L294-L297 has to have some additional logic. To actually encode, you can see how IPython.display.Video does it: https://github.com/ipython/ipython/blob/7dab272e339709a2ef155f9d992a99678e426294/IPython/core/display.py#L1187-L1207

**Comment by dmadisetti** [comment]
Oh this is super cool:

:seedling: I’m pursuing a PhD in Differential Ray Tracing for Telecommunications

I'm a PhD student working on Raytracing for X-Ray Diffraction (for material property characterization)

**Comment by jeertmans** [comment]
Thanks for taking a closer look, I really appreciate! I hope to be able to take some time for this in the next days / weeks.

> I'm a PhD student working on Raytracing for X-Ray Diffraction (for material property characterization)

oh nice! Happy to meet a Ray Tracing colleague 😁

> Edit: Sorry, Github doesn't have like a DM feature

no problem! In the future, you can reach me via my email address (listed on my personal website), or via Telegram under the same username :)

**Comment by jeertmans** [comment]
I have asked on the RevealJS's forum for help about data-uri videos, since I couldn't manage to have it working as background video: https://github.com/hakimel/reveal.js/discussions/3362.

**Comment by jeertmans** [comment]
A small but nice update @dmadisetti: someone helped my fix the aforementioned issue, see #236. This means that this will be possible (soon hopefully) to render Manim Slides within Jupyter Notebooks :D

**Comment by jeertmans** [comment]
Closing as implemented by #237

**Comment by jeertmans** [comment]
Usage example: https://eertmans.be/manim-slides/reference/magic_example.html

**Comment by dmadisetti** [comment]
Very cool; thank you!
