### ISSUE TITLE
[Bug/Simple Feature] Slides are not properly resized with the browser frame

### ISSUE THREAD

**Issue by Fairlight8** [jeertmans/manim-slides#128]
Hello! First of all, thanks for this awesome plugin, I am using Manim lately and being able to use them for interactive presentations is a nice addition. However, I found a little inconvenience.

## Context

I usually design my animations for a 1920x1080 resolution for obvious reasons, since it is the most widely used aspect-ratio. But some days ago I used a presentation made with manim + manim-slides in a projector, the typical projector found in classrooms. It had a 4:3 old aspect-ratio. Then, I found that the sides of the animation were cropped, and I had to resize the browser manually.

## Explanation

If the aspect-ratio of the browser doesn't match the aspect-ratio of the manim video files, the slides are cropped. This is because videos are inserted as RevealJS backgrounds. And by default, RevealJS backgrounds are in 'cover' mode, which scales the background until all the frame is covered. It should be in 'contain', which scales the background until all of it is visible:

### How it is currently working
![b](https://user-images.githubusercontent.com/36537992/220919693-a25a9c73-7df1-453f-b25b-09a857f90a8c.png)

### How it should work
![a](https://user-images.githubusercontent.com/36537992/220919647-4303b75d-8d5d-4fea-bdf5-121d32a0e4ff.png)

## Solution

In the RevealJS documentation, they show how to configure this background-size: https://revealjs.com/backgrounds/. Both for images and videos, it is set by the attribute data-background-size (data-background-size='contain'). I changed the attribute manually in a generated slide and it works.

I am sorry, I don't know how to do a Pull Request (I am starting to contribute to opensource projects, I have to learn soon). But I inspected your code, and I think all you have to do is to add `data-background-size="contain"` to the HTML sections render. In the file main_slides/convert.py: 

    def get_sections_iter(self) -> Generator[str, None, None]:
        """Generates a sequence of sections, one per slide, that will be included into the html template."""
        for presentation_config in self.presentation_configs:
            for slide_config in presentation_config.slides:
                file = presentation_config.files[slide_config.start_animation]
                file = os.path.join(self.assets_dir, os.path.basename(file))

                # TODO: document this
                # Videos are muted because, otherwise, the first slide never plays correctly.
                # This is due to a restriction in playing audio without the user doing anything.
                # Later, this might be useful to only mute the first video, or to make it optional.
                # Read more about this:
                #   https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#autoplay_and_autoplay_blocking
                if slide_config.is_loop():
                    yield f'<section data-background-video="{file}" data-background-video-muted data-background-video-loop></section>'
                else:
                    yield f'<section data-background-video="{file}" data-background-video-muted></section>'

It should be something like:

                    yield f'<section data-background-size="contain" data-background-video="{file}" data-background-video-muted data-background-video-loop></section>'
                else:
                    yield f'<section data-background-size="contain" data-background-video="{file}" data-background-video-muted></section>'

Unless you want to add a parameter to switch from contain to cover. I don't know if there is any particular use case for maintaining 'cover'.

**Comment by jeertmans** [comment]
Hi @Fairlight8, many thanks for your interest and the very comprehensive description of your problem.

> In the RevealJS documentation, they show how to configure this background-size: https://revealjs.com/backgrounds/. Both for images and videos, it is set by the attribute data-background-size (data-background-size='contain'). I changed the attribute manually in a generated slide and it works.

It may be a good solution, indeed. But, before going through a PR and a new feature, did you try changing the `width` and `height` attributes of the slides to match those of your video?

You can do so with:
```bash
manim-slides convert <you_scene> <some_file>.html -cwidth=<some_value> -cheigth=<some_value>
```

Otherwise, I think adding a new `data-background-size` attribute can be very easily done :-)

**Comment by Fairlight8** [comment]
I tried using those parameters, `-cwidth=... -cheigth=...`, and it didn't change anything. I have been playing with different values and ratios to see how it affected the slides, and it doesn't change. I have been reading a little bit of the template and how RevealJS works and I think that this is because the videos are in the background layer, and RevealJS applies a responsive scaling only to the elements, not the background.

Again, that's what I think given what I see, I could be wrong.

Thanks for the fast reply!! ^^

**Comment by jeertmans** [comment]
Ok then I think it is worth creating a new feature!

Let me insist that you create a Pull Request, since it is your idea :-)

Since the code changes are very simple, you could edit all the files directly on GitHub.

# 1. First fork this repository

https://github.com/jeertmans/manim-slides/fork

# 2. Make required changes (on your fork)

https://github.com/jeertmans/manim-slides/blob/b5f6a165dbecd1eed2f5f908d5cf29b86e58517e/manim_slides/convert.py#L167-L173

Before `BackgroundTransition`, create a new class:

```python
class BrackgroundSize(Str, Enum):  # type: ignore
    # From: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
    # TODO: support more background size
    contain = "contain"
    cover = "cover"
```

You do not have to implement more background size, but you can if you want :-)

Then add a new attribute here:

https://github.com/jeertmans/manim-slides/blob/b5f6a165dbecd1eed2f5f908d5cf29b86e58517e/manim_slides/convert.py#L259-L262

```python
    transition: Transition = Transition.none
    transition_speed: TransitionSpeed = TransitionSpeed.default
    background_size: BackgroundSize = BackgroundSize.contain  # Not in RevealJS
    background_transition: BackgroundTransition = BackgroundTransition.none
    pdf_max_pages_per_slide: Union[int, str] = "Number.POSITIVE_INFINITY"
```

Finally, in

https://github.com/jeertmans/manim-slides/blob/b5f6a165dbecd1eed2f5f908d5cf29b86e58517e/manim_slides/convert.py#L280-L296

add the new background size information:

```python
                if slide_config.is_loop():
                    yield f'<section data-background-size={self.background_size} data-background-video="{file}" data-background-video-muted data-background-video-loop></section>'
                else:
                    yield f'<section data-background-size={self.background_size} data-background-video="{file}" data-background-video-muted></section>'
```

# 3. Test your changes

You can install your version of Manim Slides with:

```bash
pip install git+https://github.com/Fairlight8/manim-slides.git@main
```

This, assuming that you worked on the `main` branch. Otherwise, you need to alter it to whatever branch you are working on.

With this version, you can verify that the rendering is correct for 4/3 images.

# 4. Create a Pull Request

https://github.com/jeertmans/manim-slides/compare

# Need help?

If you have any question, please feel free to reach me :-)

**Comment by Fairlight8** [comment]
Okay, I will do it when I have some free time in the evening! Thanks for the help!

One last note before I create the Pull Request. I thought that it could be a good idea to set the background of the HTML document to the background of the manim animation, in order to avoid the black bands around the animation. Do you agree? Can I include that in the PR?

**Comment by Fairlight8** [comment]
I was thinking about:

1. Reading the background color from manim. It is in config.background_color. (I don't know how or where to read this value)
2. Including it in the RevealJS section render. In the DOCs, they say you can set a background color with `data-background-color="aquamarine"`. I tried it manually and it works.

**Comment by jeertmans** [comment]
Ok, then I think it's better to leave that to another PR.

I have created a special issue for that #130

**Comment by Fairlight8** [comment]
I created a Pull Request for this Issue! Thanks a lot for the help. Please tell me if I made any mistake.

**Comment by jeertmans** [comment]
Hum I never used an enum directly, as I used the dict method. I thought it would call str, which should handle quoting, but I might be wrong. Anyway, that’s not an issue :)
https://github.com/jeertmans/manim-slides/blob/b5f6a165dbecd1eed2f5f908d5cf29b86e58517e/manim_slides/convert.py#L329
