### ISSUE TITLE
[FEATURE] read background color from `manim.config`, save it in config and use it in Manim-Slides

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#130]
### Description

As mentioned in https://github.com/jeertmans/manim-slides/issues/128#issuecomment-1443429114, it would be nice to use the save background color as the one used with Manim (or ManimGL).

A few to-dos:
- [ ] Add a new `background_color` field in https://github.com/jeertmans/manim-slides/blob/a9f53555951b490a74f00acff70c2820c293a8f9/manim_slides/config.py#L147-L149
- [ ] Read `background_color` from Manim / ManimGL config and write it somewhere in https://github.com/jeertmans/manim-slides/blob/a9f53555951b490a74f00acff70c2820c293a8f9/manim_slides/slide.py#L28-L54
- [ ] Default to presentation background color if `--background-color`/`-cbackground-color` option is not set in **present** https://github.com/jeertmans/manim-slides/blob/a9f53555951b490a74f00acff70c2820c293a8f9/manim_slides/present.py#L783-L792 and in **convert** https://github.com/jeertmans/manim-slides/blob/a9f53555951b490a74f00acff70c2820c293a8f9/manim_slides/convert.py#L271

**Comment by Fairlight8** [comment]
Hello again. I want to address this as soon as I can. I am extremely busy these days.

**Comment by jeertmans** [comment]
Hi! What do you me: do you want to be assigned to this issue, or do you want someone to work on this?

**Comment by Fairlight8** [comment]
Oh, no, sorry, I meant that I will try to implement it as soon as I can.

**Comment by jeertmans** [comment]
No problem @Fairlight8! Take you time ;)

**Comment by jeertmans** [comment]
Hello! Maybe you could create a Pull Request so that I can easily see your code changes? I don't mind reviewing code even if it's still a "draft".

> Probably it's because I never worked with pydantic, and I should learn.

That's a very good package for ensuring valid data types.

>  I thought about changing the default to a string like "scene", and changing it if necessary : if self.background_color == "scene: self.background_color=..."

I think the best to do is:
1. Change the cli default to `None`, and the type (in the `present` command) to `Optional[str]`) https://github.com/jeertmans/manim-slides/blob/a9f53555951b490a74f00acff70c2820c293a8f9/manim_slides/present.py#L783-L792
2. Check if background color is specified by the cli with `if background_color:` and then overwrite the color in the config(s).

> The other question is, how is the field in PresentationConfig advance to the code we can see in present and convert?

Similar to what is done with `present`, you could check if the user chose a color manually, and they opt for the background color in the config.

**Comment by jeertmans** [comment]
Hello @Fairlight8, any update on this? Do not hesitate if I can help :-)

**Comment by Fairlight8** [comment]
Hello @jeertmans!

Sorry, I didn't know how to continue and got busy with other stuff.

I have been learning click and pydantic to know how to continue. Very simple libraries, but I didn't know how they behaved! But I think I can continue now. Just one doubt:

### Present.py

In the presentation code, it seems like you can parse several animations, right?
```
presentations = [
        Presentation(presentation_config)
        for presentation_config in get_scenes_presentation_config(scenes, folder)
]
```
Then, you present them using:

```
app = QApplication(sys.argv)
app.setApplicationName("Manim Slides")
a = App(
        presentations,
        config=config,
        start_paused=start_paused,
        fullscreen=fullscreen,
        skip_all=skip_all,
        resolution=resolution,
        record_to=record_to,
        exit_after_last_slide=exit_after_last_slide,
        hide_mouse=hide_mouse,
        aspect_ratio=ASPECT_RATIO_MODES[aspect_ratio],
        resize_mode=RESIZE_MODES[resize_mode],
        background_color=background_color,
)
a.show()
sys.exit(app.exec_())
```
This means that you can only use one color. What if there are several scenes with different colors?

**Comment by jeertmans** [comment]
No problem @Fairlight8 :-)

> In the presentation code, it seems like you can parse several animations, right?

Yes, but you can still have a background color specific to "each" presentation, and only use `--background-color` option from command line to overwrite the background color to a desired color.

Maybe it's easier to see an example.

Recently, I added the `--start-an-scene-number` option.

https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L898-L906

The argument in `present` is:
https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L942

Therefore, if the value is not set, it will default to `None`.

Then, we call the `App` constructor with `start_at_scene_number`:

https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L991-L1007

but the argument is only really used by the `Display` class (called by the `App` constructor):

https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L318-L336

In this call to `__init__`, we set the `start_at_scene_number`:

https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L348-L349

Here, I use a small "trick" that is Python's property decorator:

https://github.com/jeertmans/manim-slides/blob/04dcf530f5f3cec6e623f7227837c64f89f83060/manim_slides/present.py#L363-L375

The `if value:` checks if the `start_at_scene_number` value is not `None`, and update the inner attribute only if it's the case.

# Summary

You make an optional `--background-color` command-line option, that only overwrite the background color in the config files if and if this option is not `None`.

This might be a bit complicated, I agree. But hopefully, I will soon add a similar feature for reading scene's resolution, and I will ping you when ready. You will be able to almost "copy-paste" the implementation and make small changes for the background color :-)

**Comment by jeertmans** [comment]
Nice work @Fairlight8 !! Is it maybe because the color is « yellow » and not an hex color ?
I think Manim provided a way to interpret their own color names into hexadecimal color (or else)

**Comment by jeertmans** [comment]
It’s seems that it may be a compression issue, and most probably when I concatenate the animations in convert, but you fixing this is not the work of this PR/issue :)

if you can juste create an issue with this very screenshot, that would be perfect!

**Comment by Fairlight8** [comment]
It looks like a compression issue. But it is weird, colors are uniform, not showing the typical compression artifacts. Either way, I'll just continue, send the pull request and create a new issue.

**Comment by jeertmans** [comment]
Thanks @Fairlight8, would you mind giving a small code to reproduce the bug?

**Comment by Fairlight8** [comment]
Of course. Here or another Issue?

**Comment by jeertmans** [comment]
Another one :)
