### ISSUE TITLE
[BUG] Low FPS on Windows

### ISSUE THREAD

**Issue by H-isaac23** [jeertmans/manim-slides#179]
### Please explain the issue you're experiencing (with as much detail as possible):

I tried using the code in the readme, and it's all good if I use the command: 
```
manim -pqh main.py Example
```
However, when I try to use manim-slides to generate the slides using the command:
```
manim-slides Example --fullscreen
```
Or even without the --fullscreen flag, the fps of the animations is lower, and the videos inside the media folder seems smoother. But when I open the videos on the slides folder, it has the same fps as the video in the media folder. 

Is there any way to make the fps the same?

**Comment by jeertmans** [comment]
Hello @H-isaac23,

Thanks for reporting this issue!

Do you have a particularly low performances computer? This might partly explain why.

If not, I surely need to investigate that a bit more! 

I know it's hard to quantify, but is the FPS drop significant, or juste noticeable?

**Comment by H-isaac23** [comment]
Here's the spec of my laptop, it's not bad but it's not that good either:
![image](https://user-images.githubusercontent.com/72616353/235851793-6b838131-3754-4c15-a257-47350a9a47c1.png)

The fps drop is noticeable, it's just like turning youtube's 720p60 back to 480 (just the fps, the resolution is fine), I can do just fine with it but I'd prefer if the slides can match the fps of the videos. Are my specs fine or do I just have to live with it?

**Comment by jeertmans** [comment]
Feels like your config should be ok. The main thing that could cause problems here is that your computer is potentially throttling the CPU frequency to reduce the battery usage.

It seems like you are using Windows, and this OS allows controlling the CPU freq (at least with Windows 10). Did you check if your computer was plugged to some power supply? Sometimes, this is sufficient to turn the CPU frequency up and gain performances.

**Comment by H-isaac23** [comment]
I have it plugged but it's still the same. Is there anything I can try doing just to see if it will improve?

**Comment by H-isaac23** [comment]
I tried more examples from example.py
I noticed that maybe it's not actually an fps drop, but the animation is just playing slower whenever I use the command "manim-slides Scene". That's what I noticed after trying more examples. My laptop is plugged on a power source so it probably on its best performance. 
What should be my approach here?

**Comment by H-isaac23** [comment]
I also tried converting the slides into powerpoint. The presentation in powerpoint is normal, it's just like the videos rendered on the media folder. So I really think the video is just playing slower. Maybe it's just my laptop

**Comment by jeertmans** [comment]
Ok, so I created #180 to add a few more debugging tools to make it easier for us to find where the problem is :-)

You can install this version using:

```bash
pip install -U git+https://github.com/jeertmans/manim-slides@debug-perf
```

You can check you have the latest version with:

```bash
manim-slides -v
> manim-slides, version 4.13.0-alpha
```

If you have problem installing the version from `git`, do not hesitate to ask for help :-)

If you run the following command:

```bash
manim-slides BasicExample -v PERF
```

You should see the following logs:

![image](https://user-images.githubusercontent.com/27275099/235928938-03dbb221-fbfa-4a62-9ce1-8d409b1f75a2.png)

We are interested in `PERF` and `WARNING` messages. The `PERF` shows how much time it takes for Manim Slides to process one frame. So the number on the left should be lower than that on the right, to achieve the desired FPS.

`WARNING`s will occur if that is not possible. A few ones are ok, but too many indicate that your computer takes too much time processing the video.

If you can check that locally, this would help me a lot to understand if the problem is about performances or not :-)

**Comment by H-isaac23** [comment]
Here are all of the warnings that I see:
![image](https://user-images.githubusercontent.com/72616353/235935393-330220e6-a484-47ad-bf41-ba871fc1bcb4.png)

![image](https://user-images.githubusercontent.com/72616353/235935723-9e055333-4e38-44be-848f-173f34e888a4.png)

![image](https://user-images.githubusercontent.com/72616353/235936175-43fab0cc-9904-4f68-a374-20c8d3023194.png)

It seems like it's normal? I don't know, there's a clear difference for me whenever I use  ```manim -pqh main.py Example``` versus when I use ```manim-slides Example --fullscreen```. The former looks smoother while the latter looks like it's slowed down a little bit, which looks to me like an "fps drop".

**Comment by H-isaac23** [comment]
I tried it out, but I'm not noticing any difference, there might be some but it's not noticeable, at least for me.

**Comment by jeertmans** [comment]
Hum, quite weird ^^'

What about the convert features, do the videos lag when presented with HTML or PPTX? (just for the comparison)

**Comment by H-isaac23** [comment]
That was actually one of the things I said earlier. I haven't tried with html, but in pptx it looks exactly like the ```manim -pqh``` command.

**Comment by jeertmans** [comment]
I'm happy if the convert feature does what you need :) 

I hope I will be able to solve understand optimize a bit the code in the future, hoping this will solve this problem

**Comment by torannn** [comment]
I'm experiencing the same FPS dropped with the inner presentation, but works fine with hmtl and pptx. I'm also using Windows so I guess Windows is the main cause of the problem.

**Comment by jeertmans** [comment]
Did you try the 5.0.0-rc1 version? The new video player should be better

**Comment by Iv90An** [comment]
> Did you try the 5.0.0-rc1 version? The new video player should be better

May I ask what you mean by "the 5.0.0-rc1 version"? Is this a new version of manim-slides or is it some other software?

**Comment by jeertmans** [comment]
@Iv90An it is a pre-release version. So it is not advertised as the latest version by pypi, but you can still install it with `pip install manim-slides==5.0.0-rc1`.
