### ISSUE TITLE
[BUG] --use-template is not working

### ISSUE THREAD

**Issue by abul4fia** [jeertmans/manim-slides#181]
### Description

When the --use-template option is used, the error `Option 'template': str type expected` is produced.

Example:

```shell
manim-slides convert --use-template slides-template.html Test.html
[...]
Error: 1 error(s) occured with configuration options for 'html', see below.
Option 'template': str type expected
```

Apparently there is a conflict between the type which `convert.convert()` is receiving in its parameter `template`, which is of type `Path`, and the one Pydantic is expecting and validating, which is `str`.

The problem can be solved by adding these lines at the beginning of `convert.convert()`:

```python
    if template:
        template = str(template)
```

### Version

manim-slides, version 4.13.0

### Platform

Linux

**Comment by jeertmans** [comment]
Hello @abul4fia, nice catch for this! I've pushed a fix in #182, and will hopefully soon release it under `v4.13.1` :-)

Thanks for your help!
