### ISSUE TITLE
[FEATURE] Installation of manim and/or manimgl via manim-slides 

### ISSUE THREAD

**Issue by behollister** [jeertmans/manim-slides#194]
### Description

currently either manim or manimgl need to be installed separately and prior to manim-slides. 

each, in turn, have their own set of dependencies.

best if manim-slides handles installing manim (or manimgl) as well, if not already present on target system.

request related to jose review: https://github.com/openjournals/jose-reviews/issues/206

**Comment by jeertmans** [comment]
Hello @behollister!

This was already addressed in #170 and approved #173 as a solution (see GitHub approve).

Is it ok for you?

**Comment by behollister** [comment]
Yes, all of the issues have been resolved.

Regards,
Brad

Brad E. Hollister, Ph.D.

Department of Computer Science
Californian State University Dominguez Hills
Office: NSM B218
Phone: 864-395-5560
________________________________
