### ISSUE TITLE
[FEATURE] Export to png / pdf

### ISSUE THREAD

**Issue by augustindelecluse** [jeertmans/manim-slides#196]
### What

Being able to export the slides as png or pdf will help in the following situations:

- Issue with the computer managing the presentation, and backup slides must be used
- Sharing presentations with other people that do not have manim installed

The animations themselves will obviously be lost, but the feature is still relevant in some cases.

### How

I'm not familiar with the rendering process used in manim, but I guess looping through the mp4's generated by manim and taking the last image generated in each video, and then combining them, will be sufficient. Alternatively, taking the last state before the call to `next_slide()` is also sufficient. The images could then be combined in a pdf file, for instance by creating a beamer presentation using LaTeX, and taking each image as one slide.

When looking at the [features](https://eertmans.be/manim-slides/features_table.html) described in the documentation, I could not find this one, hence this issue.

**Comment by jeertmans** [comment]
Hello @augustindelecluse,

This should not be hard, since I already do a similar thing when exporting to PPTX.

I'm currently looking at the various PDF libraries, to see which one I should rather use.

**Comment by jeertmans** [comment]
@augustindelecluse, would you mind testing the new feature in dev.?

```
pip install git+https://github.com/jeertmans/manim-slides@convert-pdf
```
