### ISSUE TITLE
Low resolution in Windows

### ISSUE THREAD

**Issue by arashash** [jeertmans/manim-slides#20]
Hi there. Thank you so much for maintaining this.

Unfortunately, I couldn't get the HD resolution in Windows. Here's how it looks like:
![image](https://user-images.githubusercontent.com/15813444/191139115-f5c4bf9b-fdf7-4143-8d5f-4c1d3b69fb18.png)
but supposed to be:
![image](https://user-images.githubusercontent.com/15813444/191139386-aba3b54b-cb35-4db3-b4a5-2befd842274d.png)

I tried setting the resolution to 1920x1080, but it didn't work.

**Comment by jeertmans** [comment]
Hi @arashash , thank you for your issue!

I just tested a fix in Windows and it seems to work quite well, see #22 . Would you mind testing it?

You can install it using:
```bash
pip install git+https://github.com/jeertmans/manim-slides@fix-window-quality
```

**Comment by arashash** [comment]
Thank you so much @jeertmans 
It looks much better now:
![image](https://user-images.githubusercontent.com/15813444/191283485-f6b8da44-4189-4aa2-bd4b-0bea8e845191.png)

**Comment by arashash** [comment]
Is there a way to increase the quality further?

**Comment by jeertmans** [comment]
Did you try to increase the rendering quality?
On my side, I will try different interpolation methods.

**Comment by arashash** [comment]
yea, I tried: 
`manim-slides SkipConnection --fullscreen --resolution 1920 1080`

btw I'm wondering if we could skip the resizing step if the fullscreen resolution matches the video? I think that's a very common usecase. Since we generally we have HD resolution and monitors

**Comment by jeertmans** [comment]
I removed the "useless" resizing when resolutions match. However, `--fullscreen` resolution does not seem to match HD resolution, at least on my desktop (even though it should, I think).

Then, I added an optional flag for interpolation method, because I can't really see one that is better than all the others.

**Comment by jeertmans** [comment]
Yeah… I really don’t know why I can’t have the same quality on Windows and on Linux…

And what happens if you increasing the rendering quality (so with manim or manimgl)?

**Comment by arashash** [comment]
I think I found the issue. In windows, there's the option of scaling:
![image](https://user-images.githubusercontent.com/15813444/191304986-9edb8d4d-fb16-4b1f-ae73-02b2a92141f4.png)
When I set it to 100 it looks perfect:
![image](https://user-images.githubusercontent.com/15813444/191305126-c124eb61-7cff-43ff-b166-a9cedbe61c6d.png)

**Comment by jeertmans** [comment]
Wow, nice! Where is this option? I might document that in the README.

**Comment by arashash** [comment]
Yaay! On the main page of settings.
![image](https://user-images.githubusercontent.com/15813444/191306387-7d4636a4-4987-4fc8-85ad-ab33ea256620.png)
