### ISSUE TITLE
[FEATURE] Render full video based on keystroke history

### ISSUE THREAD

**Issue by chunribu** [jeertmans/manim-slides#21]
As the title, is it possible to render a full video based on keystroke history using ffmpeg? That could be another useful feature.

**Comment by jeertmans** [comment]
Hi @chunribu ! Thank you for your question :-)

If I understand well, you want to present slides, record keystrokes at the same time, and then have a video file that shows exactly what has been shown during the slide presentation?

If so, this is currently not implemented, but should be very easy to do.

**Comment by jeertmans** [comment]
Well, this is harder than expected, because rendering or saving frames in the same time as presenting, actually slows down the presentation.

I might need to implement some kind of `Presentation.get_current_state`, then save the state for every frame, and re-read the same files after the presentation to generate output video.

**Comment by chunribu** [comment]
Hi @jeertmans 
Glad to see you considering this advice. Thanks for letting me know how it goes. 
Please continue at your own pace, and have a nice day!

**Comment by jeertmans** [comment]
Hi @chunribu , when you have time, can you try to new feature, see #25 ?

To test it, please install:
```bash
pip install git+https://github.com/jeertmans/manim-slides@record-presentation
```

Thanks!

**Comment by jeertmans** [comment]
I am re-opening this as this might be worth reconsidering the way we write the video: maybe use PyAV instead?

**Comment by jeertmans** [comment]
Oops, forgot I removed this feature in #243. It's just probably better to use a separate tool to record the screen.
