### ISSUE TITLE
[FEATURE] Allow to complete loop before going to next slide

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#254]
### Discussed in https://github.com/jeertmans/manim-slides/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **torannn** August 23, 2023</sup>
I've seen a similar project named Manim Editor. I think the feature complete_loop is quite useful. Currently, if we use the loop and press the next button, the animation will end immediately. It creates an unsmooth transition between animations. I think we can create the complete_loop feature similar to Manim Editor. When the user press the next button, the complete_loop force the animation to be finished, then continue running the next animation.
You can check out the example created by manim editor here [https://manimcommunity.github.io/manim_editor/Tutorial/index.html](url).</div>

**Comment by jeertmans** [comment]
Hello @zain93393, thanks for your interest in helping me!

First, make sure to read the [contributing guide](https://eertmans.be/manim-slides/contributing/index.html).

Next, you should only edit the code in https://github.com/jeertmans/manim-slides/blob/main/manim_slides/present/.

The idea I propose it to have a CLI option `--next-terminates-loops` that will allow user to turn a loop into a plain slide (i.e., not looping) upon pressing `NEXT`.

This is the code that is processed when pressing `NEXT`:

https://github.com/jeertmans/manim-slides/blob/bbe8b960304936dfe043614d47034451e12ab007/manim_slides/present/player.py#L298-L303

I think you should modify the `else` clause to something like

```python
elif self.next_terminates_loops and self.medial_player.loops() != 1:
    self.media_player.setLoops(1)
else:
    self.load_next_slide() 
```

Of course, you will need to add a new option to the Player's `__init__` method:

https://github.com/jeertmans/manim-slides/blob/bbe8b960304936dfe043614d47034451e12ab007/manim_slides/present/player.py#L42-L55

Finally, you need to add a CLI option to 
https://github.com/jeertmans/manim-slides/blob/bbe8b960304936dfe043614d47034451e12ab007/manim_slides/present/__init__.py#L220-L233

and document it (see other `click.option` as examples) so that the user can specify the option via the terminal.

Tell me if you need further help :-)

**Comment by zain93393** [comment]
hey @jeertmans, this error is coming up when I am trying to push the changes 

![image](https://github.com/jeertmans/manim-slides/assets/75107982/84c33217-0818-48d7-ba3e-fb240300685f)

can you help me with this?

**Comment by jeertmans** [comment]
Seems that you are trying to push your virtual environment, which contains very large files, which you should not do.

Usually, you want to ignore that folder, by adding a new line to `.gitignore`.

Check the [Undoing Your Last Commit (That Has Not Been Pushed)](https://www.nobledesktop.com/learn/git/undo-changes) section, to undo your commit. Next, modify `.gitignore` to include your virtual env. Then, re-commit your files and push.

**Comment by jeertmans** [comment]
After testing, I am afraid this might not be possible: `QMediaPlayer.setLoops(1)` does not seem to apply to the current loop. Actually, setting the loop to `1` finishes the current loop, and does two more loops before reaching `EndOfMedia`. I will open a PR showing my work, but this does not work at the moment.
