### ISSUE TITLE
[FEATURE] Docker image

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#259]
### Description

The idea is to create a Docker image to facilitate installing Manim Slides on all computers.

A simple solution would be to use ManimCE's Docker image, but this would mean no support for ManimGL.

**Comment by Rajdeep1311** [comment]
I would like to work on this during the hacktoberfest

**Comment by Rajdeep1311** [comment]
can you assign me?

**Comment by jeertmans** [comment]
Hello, thanks for suggesting!

can’t wait to see some proposal :)

**Comment by Rajdeep1311** [comment]
I guess example.py contains the main code of the project.

**Comment by jeertmans** [comment]
Hello, no `example.py` contains usage examples. The main code is the Python library, placed in the `manim_slides` folder.

**Comment by Rajdeep1311** [comment]
Okay sir

**Comment by Rajdeep1311** [comment]
The main.py file is the main code file, right?

**Comment by jeertmans** [comment]
The main file is only the file that is called to run the command line script.
But the package contents is defined is multiple files, such that there is no one unique file that contains everything.

**Comment by Rajdeep1311** [comment]
Sir I need some help, actually, I am finding it challenging to write a Dockerfile for this project

**Comment by jeertmans** [comment]
Could you explain what is challenging? What did you try?

**Comment by Rajdeep1311** [comment]
I tried writing a Dockerfile, I want to know more about what is the main issue,

**Comment by jeertmans** [comment]
Well we need a docker file that setup everything needed to run Manim Slides

**Comment by Rajdeep1311** [comment]
Okay, I guess getting more involved in the community would help me

**Comment by Rajdeep1311** [comment]
Can I know what is the problem with the official image that is already in the Dockerhub

**Comment by jeertmans** [comment]
It does not contain the Manim slides package

**Comment by harsh18262** [comment]
Is this still required or completed?

**Comment by jeertmans** [comment]
Yes @harsh18262, you can have a try :)

**Comment by jeertmans** [comment]
Closes by #355
