### ISSUE TITLE
[FEATURE] make `self.start_loop` call `self.next_slide`

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#266]
### Description

Currently, one must call `self.next_slide` prior to `self.start_loop`.
On top of that, multiple calls to `self.next_slide` are not merged.

I think it might be better to automatically merge empty slides, and call `self.next_slide` within `self.start_loop`, so the user does not need to care about this.

A future improvement might be to have `self.next_slide(loop=True)` instead.

A thing to check is compatibility with ManimGL, because ManimGL's `self.wait` does not actually call `self.play`.

**Comment by indra057** [comment]
i would like to contribute can you assign me

**Comment by jeertmans** [comment]
Yes of course, have a try ;-)

@indra057

**Comment by jeertmans** [comment]
Supersed by #294
