### ISSUE TITLE
[FEATURE] make `self.wipe` and `self.zoom` classes instead of methods

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#267]
### Description

The current solution was adopted because simpler, but using classes would be better to be closer to what ManimCE does.

Also, `self.wipe` and `self.zoom` could be replaced so that they automatically call `self.play` and default to updating the canvas.

**Comment by indra057** [comment]
hii i want to contribute to this issue can you assign me plzz ..(i want to be a part of hactoberfest)

**Comment by OmarEid451** [comment]
I would like to contribute please

**Comment by jeertmans** [comment]
Either you can each work on your separate solution, and do a PR and I will try to pick the best one, or you can try to collaborate :-)

Do not hesitate if you need help!

**Comment by OmarEid451** [comment]
Which file are you keeping your classes in? I'm having a hard time finding where the code you would like changed is.

**Comment by jeertmans** [comment]
The classes should be declared in slide.py, but the imports from Manim or ManimGL should be performed first in manim.py
