### ISSUE TITLE
Unable to use `Slide.zoom`, or `Zoom` animation

### ISSUE THREAD

**Issue by rkshthrmsh** [jeertmans/manim-slides#303]
### Please explain the issue you're experiencing (with as much detail as possible):

I am on `manim-slides` with `manim` and `manimgl` installed. The versions can be seen here:
```
$ pip list | grep manim
manim                         0.17.3
manim-slides              4.16.1
manimgl                      1.6.1
```

However, even the simple `ZoomExample`(https://eertmans.be/manim-slides/reference/api.html#manim_slides.slide.Slide.zoom) in the documentation is not working. In fact, looking at the code here in the repo, it seems that the implementation of the `zoom` method in the installed `manim-slides` is quite different. From the install location:
```python3
   def zoom(
   # --snip--
   ) -> AnimationGroup
        scale_in = 1.0 / scale
        scale_out = scale

        if out:
            scale_in, scale_out = scale_out, scale_in

        animations = []

        for mobject in future:
            animations.append(FadeIn(mobject, scale=scale_in, **fade_in_kwargs))

        for mobject in current:
            animations.append(FadeOut(mobject, scale=scale_out, **fade_out_kwargs))

        return AnimationGroup(*animations, **kwargs)
```

**Comment by jeertmans** [comment]
Hello @rkshthrmsh, you were using the v4 of Manim Slides, but the documentation was for the v5.

I just released v5, can you try upgrading version with `pip install -U manim-slides` and test it everything works?

**Comment by rkshthrmsh** [comment]
Thanks, @jeertmans. That solved it!
