### ISSUE TITLE
[FEATURE] Speaker Notes section 

### ISSUE THREAD

**Issue by harshit-codes** [jeertmans/manim-slides#311]
### Description

For each 'Slide' have a list of bullet points/ markdown notes reserved only for speaker, viewable only on a secondary screen. 

Eg: https://quarto.org/docs/presentations/revealjs/#speaker-notes

**Comment by jeertmans** [comment]
Hey! This is a very good suggestion!
I long wanted to add a second screen in the `present` mode to display presenter-only information, but this is not so easy to do. I guess a good starting point for PySide6 would be: https://stackoverflow.com/questions/66986295/how-to-create-a-video-player-with-2-windows-with-the-same-video.

On the other hand, we can just add information to slides using `self.next_slide(info="""")`, add it to the config file, and display it in either `present` or with RevealJS.

I'll see when I have time to work on that.
