### ISSUE TITLE
[FEATURE] Build on top of Reveal JS

### ISSUE THREAD

**Issue by harshit-codes** [jeertmans/manim-slides#312]
### Description

Reveal JS has a lot of good feature for Presentation. Building on top of it would be great. 

FEATURES
[Vertical Slides](https://revealjs.com/vertical-slides/)
[Auto-Animate](https://revealjs.com/auto-animate/)
[Auto-Slide](https://revealjs.com/auto-slide/)
[Speaker View](https://revealjs.com/speaker-view/)
[Scroll View NEW](https://revealjs.com/scroll-view/)
[Slide Numbers](https://revealjs.com/slide-numbers/)
[Jump to Slide NEW](https://revealjs.com/jump-to-slide/)
[Touch Navigation](https://revealjs.com/touch-navigation/)
[PDF Export](https://revealjs.com/pdf-export/)
[Overview Mode](https://revealjs.com/overview/)
[Fullscreen Mode](https://revealjs.com/fullscreen/)

**Comment by jeertmans** [comment]
Hello! What do you mean to build on top? Because you can modify the RevealJS template to access the features you want

**Comment by jeertmans** [comment]
Closing as it did not receive any response in a long time. Feel free to re-open it if you think this is necessary.
