### ISSUE TITLE
[BUG] HTML slides flicker when using `-cdata_uri=true`

### ISSUE THREAD

**Issue by JohnyMarley** [jeertmans/manim-slides#344]
### Description

Hello!
When compiling all slides into one html file, everytime I switch from one animation to another, the whole slideshow goes black for a splitsecond before going back to the correct content. Is this expected behaviour?

### Version

manim-slides 5.0.0

### Platform

linux mint

**Comment by jeertmans** [comment]
Hello! How "large" is your presentation (i.e., the number of animations it includes, or the resulting HTML size).

Does this problem disappear when you turn `-cdata_uri=false`?

The "issue" with `-cdata_uri` is that (1) the HTML file becomes quite large and (2) your computer has to first decode the video "on the fly", when you switch slides. So unless you really need "one file that contains everything", you are better using the default options and loading video from separate files.

**Comment by JohnyMarley** [comment]
Hello again! 
The problem goes away when i use -cdata_uri=false. But still presist even just for two slides. Going from an svg to a titleslide. But you are telling that the "flickering" is expected behavior?

thank you for the quick reply!

**Comment by jeertmans** [comment]
Well slides are not preloaded, so there is always a certain time between two slides. This time will depend on your PC, your internet connection if you are reading slides from a remote website, and the size of each slide.

**Comment by JohnyMarley** [comment]
I see! Thanks for the clarification!
I guess we can close this issue then!
