### ISSUE TITLE
[FEATURE] Add a digital clock on each slide of the html output

### ISSUE THREAD

**Issue by gsong-math** [jeertmans/manim-slides#356]
### Description

Would it be possible to add a digital clock on each slide of the html output? Could this be an option on the reveal.js template?

**Comment by jeertmans** [comment]
Hello, I am not sure to visualize what you are proposing. Could you provide an example image or else?

**Comment by gsong-math** [comment]
Sure, it is something like this. 
<img width="1311" alt="Screen Shot 2024-01-20 at 9 09 53 AM" src="https://github.com/jeertmans/manim-slides/assets/124700224/57381cbb-23c9-46aa-af44-e97f89b9c313">

A digital clock displays the current time in the corner of each slide.

**Comment by jeertmans** [comment]
Well you can use a custom template for RevealJS (see CLI reference), but I can see if I find a nice component to add to the default template. 
Do you have an exemple html code that would render this clock?

Did you try the speaker mode when pressing S?

**Comment by gsong-math** [comment]
Thanks a lot for the response. Yes, the speaker mode displays the time. It might still be sweet to have a time clock on the slides. Sometimes, the presenter might need to walk away from the computer and look at the projected screen. 

I am sorry that I am not good at html coding and do not have an existing code for rendering the clock.

**Comment by jeertmans** [comment]
I will try to write an example tutorial to show how to modify the template for that purpose.

In the meantime, you could do that yourself, see this page: http://www.java2s.com/Tutorials/Javascript/Javascript_Data_Type_How_to/Date_Clock/Create_auto_refresh_clock.htm.

You can create a new file from https://github.com/jeertmans/manim-slides/blob/main/manim_slides/templates/revealjs.html, and add the code to render the clock (not sure how to add it on top of every slide though).

Then, render using `manim-slides convert ... --use-template <PATH-TO-YOUR-TEMPLATE-FILE>`.

**Comment by gsong-math** [comment]
Thanks a lot for the information. I guess I could use the provided information to render the clock in html.

The issue is how to add it on top of every slide. In the reveal.js template, we could tweak it to add some extra things like progress bar, page number to every slide. I was just wondering whether it would also be possible to add a clock there.

**Comment by gsong-math** [comment]
I made it work through manually inserting the following script in the converted html file.

Would it be possible to modify the template file for this purpose? It is a little tedious to edit the html file afterwards.

```html
 <!-- Add dynamic content to each section dynamically using JavaScript -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var revealContainer = document.querySelector('.reveal');
    // Append dynamic content to each section
    var sections = revealContainer.querySelectorAll('.slides > section');
    sections.forEach(function (section) {
      // Create a new clock container
      var clockContainer = document.createElement('div');
      clockContainer.className = 'clock';
      
      // Append the new clock container to the section
      section.appendChild(clockContainer);
    });

    // Function to update the clock content
    function updateClock() {
      var now = new Date();
      var hours = now.getHours();
      var minutes = now.getMinutes();
      var seconds = now.getSeconds();

      // Format the time as HH:MM:SS
      var timeString = padZero(hours) + ":" + padZero(minutes) + ":" + padZero(seconds);

      // Update the content of all clock containers
      var clockContainers = document.querySelectorAll('.clock');
      clockContainers.forEach(function (container) {
        container.innerText = timeString;
      });
    }

    // Function to pad zero for single-digit numbers
    function padZero(number) {
      return number < 10 ? "0" + number : number;
    }

    // Update the clock every second
    setInterval(updateClock, 1000);

    // Register a reveal.js event to update the clock on each slide change
    Reveal.addEventListener('slidechanged', function (event) {
      updateClock();
    });

    // Initial update
    updateClock();
  });
</script>

<style>
  .clock {
    position: fixed;
    bottom: -1000px;
    left: 10px;
    font-size: 24px;
    font-family: "Arial", sans-serif;
    color: #333;
  }
</style>
```

**Comment by gsong-math** [comment]
Never mind. I figured it out. I just need to add the script into the template html file. It works perfectly now.

Thanks a lot for the help.

**Comment by gsong-math** [comment]
There is still an issue about the position. In the style of clock, if using bottom: 0px, the clock will stay on the left middle of the slide. I used bottom: -1000px to push it down. But when using full screen, it went up a little bit. Looks like its position is not fixed in the slide.

**Comment by jeertmans** [comment]
Nice! Can you share the template here please?

**Comment by gsong-math** [comment]
Sure, here is the [tweaked template](https://github.com/gsong-math/manim-slides/blob/main/manim_slides/templates/my_revealjs.html) to include a clock at the bottom of each slide.
