### ISSUE TITLE
[BUG] Example from readme does not work on windows

### ISSUE THREAD

**Issue by MarcusVoelker** [jeertmans/manim-slides#359]
### Description

manim-slides and manim are installed in a virtual environment via conda.

Trying to run the BasicExample from the readme gives

```
(c:\Users\voelker\Documents\CFFAP\Manim\testing\.conda) PS C:\Users\voelker\Documents\CFFAP\Manim\testing> .\.conda\Scripts\manim-slides.exe render scene.py BasicExample     
Usage: manim-slides present [OPTIONS] [SCENES]...

Error: Invalid value for '--folder': Directory 'slides' does not exist.
```

Creating the missing folder instead gives

```
(c:\Users\voelker\Documents\CFFAP\Manim\testing\.conda) PS C:\Users\voelker\Documents\CFFAP\Manim\testing> .\.conda\Scripts\manim-slides.exe render scene.py
Usage: manim-slides present [OPTIONS] [SCENES]...

Error: File slides\render.json does not exist, check the scene name and make sure to use Slide as your scene base class
```

Using `present` instead of `render` also does not help:

```
(c:\Users\voelker\Documents\CFFAP\Manim\testing\.conda) PS C:\Users\voelker\Documents\CFFAP\Manim\testing> .\.conda\Scripts\manim-slides.exe present scene.py BasicExample
Usage: manim-slides present [OPTIONS] [SCENES]...

Error: File slides\scene.py.json does not exist, check the scene name and make sure to use Slide as your scene base class
```

### Version

5.0.0

### Platform

Windows

**Comment by jeertmans** [comment]
Hello @MarcusVoelker, creating those file manually will not help, as they need to be generated during the rendering process :-)

The command `\.conda\Scripts\manim-slides.exe render scene.py BasicExample` will only work as of Manim Slides v5.1, which I hope to release soon, sorry for the mismatch between documentation and releases :/

**Comment by jeertmans** [comment]
In the meantime, you can render using `manim render scene.py BasicExample` and present after.
The `render` command was added in v5.1.

**Comment by MarcusVoelker** [comment]
> creating those file manually will not help, as they need to be generated during the rendering process :-)

I figured, but I thought I'd include that I tried it, covering all bases.

> In the meantime, you can render using `manim render scene.py BasicExample` and present after.

Yep, that works beautifully, thanks for the quick reply!

**Comment by jeertmans** [comment]
Hi @MarcusVoelker , just to notice you that v5.1 was just released :)
