### ISSUE TITLE
chore: add pull request template

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#36]
# What

I'd like to make this repo easier to manage by creating a template for pull requests.

The documentation for creating templates on GitHub can be found here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository.

# What to include in the template

Here is what I would like to find in the template:

* a description section
* does this solve an issue? If so, reference the issue, or describe it
* some checkboxes to make stating
  * [ ] I understand that my contributions needs to pass the checks
  * [ ] If I create new functions / methods, I documented them and add type hints
  * [ ] If I modified already existing code, I updated the documentation accordingly
* additional contents: images, error output, ...

**Comment by ahmedsilat44** [comment]
Hey @jeertmans I would like to work on this issue. Can you assign it to me. Thanks 😄

**Comment by jeertmans** [comment]
Hi @ahmedsilat44! Sure, go on ;-)
Do not hesitate to ask questions if you have any!

**Comment by ahmedsilat44** [comment]
If you want to add more issue templates I would like to work on that too. Let me know if you do or if u you want to give someone else the chance to contribute 😄

**Comment by jeertmans** [comment]
@ahmedsilat44, I actually realized I wrote « Feature Request » as a title but the contents of this issue is related to creating a « Pull Request » template.
Anyway, I am very happy with #39 ans I will merge it soon :)

If you want, you can create an issue template (bug report), see #35 or you can also now create a « Pull Request » template, see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by jeertmans** [comment]
Nice, thanks @ahmedsilat44!
