### ISSUE TITLE
[QUESTION] Add a small interval between slides

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#387]
### Description

In manimgl I can add **self.wait( )** to add a stop point wherever I need. However, I have no idea about how to add a small interval in a slide. I tried add **self.next_slide( )** but it doesn't worked. The animation never stoped even it met a **self.next_slide( )**  So what should I do to achieve that purpose? Thx a lot!

**Comment by jeertmans** [comment]
Hello! I am not sure to understand what you are referring to as a *small interval*.

In general, you can just call `self.wait(t)` to make your slide a bit longer. If you want to add a wait between each slide, then check [`wait_time_between_slides`](https://manim-slides.eertmans.be/latest/reference/api.html#manim_slides.slide.Slide.wait_time_between_slides).

If you want to have a purely static slide, then just add:

```python
def construct(self):
    # my code ...

    self.next_slide()
    self.wait(1)
    self.next_slide()

    # my code ...

```

This will add a slide that lasts 1 second and does nothing.

**Comment by semikernel** [comment]
> Hello! I am not sure to understand what you are referring to as a _small interval_.
> 
> In general, you can just call `self.wait(t)` to make your slide a bit longer. If you want to add a wait between each slide, then check [`wait_time_between_slides`](https://manim-slides.eertmans.be/latest/reference/api.html#manim_slides.slide.Slide.wait_time_between_slides).
> 
> If you want to have a purely static slide, then just add:
> 
> ```
> def construct(self):
>     # my code ...
> 
>     self.next_slide()
>     self.wait(1)
>     self.next_slide()
> 
>     # my code ...
> ```
> 
> This will add a slide that lasts 1 second and does nothing.

The third method is useful for me. SInce I have many animations in a slide, I just want to play them one by one, it can surely meet my requirement. Thank you!
