### ISSUE TITLE
[Question] Are all dependencies needed for manim-slides[magic]?

### ISSUE THREAD

**Issue by dmadisetti** [jeertmans/manim-slides#393]
### Please explain the issue you're experiencing (with as much detail as possible):

Is pyqt6 required for just the magics install?
Just wondering if there's a working dependency subset

**Comment by dmadisetti** [comment]
Edit: according to the pytoml

**Comment by jeertmans** [comment]
Hello!

No, as you can see below, you do not need Qt bindings to use the `magic` feature. The same applies for the `sphinx-directive` feature.

https://github.com/jeertmans/manim-slides/blob/a85f1c40369428b7bd948e4b809308b4ca9ee26c/pyproject.toml#L58-L68

Does it answer your question? :-)

**Comment by dmadisetti** [comment]
qtpy is listed under deps though?

https://github.com/jeertmans/manim-slides/blob/a85f1c40369428b7bd948e4b809308b4ca9ee26c/pyproject.toml#L31

**Comment by jeertmans** [comment]
> qtpy is listed under deps though?
> 
> https://github.com/jeertmans/manim-slides/blob/a85f1c40369428b7bd948e4b809308b4ca9ee26c/pyproject.toml#L31

Yep, but it does not require any Qt binding directly. I could hide put it behind a feature to remove it from the default dependencies, but it doesn’t matter much I think.

**Comment by dmadisetti** [comment]
No biggie, was just wondering how best to package this

**Comment by jeertmans** [comment]
But that was a great question! I might consider removing it for the next release
