### ISSUE TITLE
Bug: GLib-GObject Error

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#394]
### Description

The manim-slides can render normally but can't present. 
After input **manim-slides present Test** in terminal prompt, it returns:
```bash
(python:7792): GLib-GObject-WARNING **: 14:14:17.449: g_type_instance_get_class_private() requires a prior call to g_type_add_class_private()
Segmentation fault (core dumped)
```
It seems quiet wired because in my another laptop everything works well. So how could I do to fix that error? Thx a lot:)

### Version

manim-slides, version 5.1.3

### Platform

Ubuntu 22.04

**Comment by semikernel** [comment]
I figured it out by installing using pipx, now it works well!

**Comment by jeertmans** [comment]
Happy you solved your issue! I guess this was caused by a broken installation of Qt bindings.
