### ISSUE TITLE
[DOC] Add example gallery

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#407]
Many users have created (and shared) very nice presentations made with Manim Slides.

This would be great to create a page referencing some of those examples!

Either a dummy list of websites / pages, or a mosaic gallery with thumbnails.

It would also be nice to add a link check on the Sphinx documentation to avoid linking to sites that do not exist anymore :-)

**Comment by semikernel** [comment]
Hi, there! I have made several beautiful slides, how can I upload my examples?

**Comment by jeertmans** [comment]
Hey @semikernel, did you look at the [manim-slides-starter](https://github.com/jeertmans/manim-slides-starter) repository?
