### ISSUE TITLE
chore: more issue templates

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#42]
# What

With #39 and #40, users can now create issues based on template. However, I'd like to have more template, in line to what is done in the [numpy/numpy](https://github.com/numpy/numpy) repository: https://github.com/numpy/numpy/issues/new/choose.

I would love to have templates for
- [ ] Documentation
- [ ] Question/Help/Support

You can get inspiration from the Numpy repository (see above), but I won't be using external links.

# How to

Please, read already existing files in [ISSUE_TEMPLATE](https://github.com/jeertmans/manim-slides/tree/main/.github/ISSUE_TEMPLATE), and get some inspiration from https://github.com/numpy/numpy/issues/new/choose too.

**Comment by harisaisundhar** [comment]
Sounds pretty straight forward, I can get this done. Can I be assigned for this ?

**Comment by jeertmans** [comment]
Yes, of course @harisaisundhar! Thank you for your interest!

**Comment by harisaisundhar** [comment]
@jeertmans Do we have a dedicated email to receive questions ?

**Comment by jeertmans** [comment]
@harisaisundhar Not for the moment, and it’s not planned. I prefer that people take contact via GitHub only.

**Comment by harisaisundhar** [comment]
Sure! In which case the questions will be tagged with the "question" tag and an issue would be created. Does that sound good to you ?

**Comment by jeertmans** [comment]
Looks good to me @harisaisundhar !

**Comment by harisaisundhar** [comment]
@jeertmans Have created a PR for the Support template. Pls do review them. Thnx
