### ISSUE TITLE
[BUG] Problem about Rust during installation.

### ISSUE THREAD

**Issue by hcq11419** [jeertmans/manim-slides#433]
### Please explain the issue you're experiencing (with as much detail as possible):

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jeertmans** [comment]
Hello @hcq11419, thanks for posting your question!

An important part of the error message is missing and I cannot help without knowing more understand.

However, I have a strong feeling that your error is related to the package rtoml, see #398. I will soon publish a temporary fix (#432), but you should be able to fix it by yourself by following the hints in #398.

Can you confirm if that is the same issue? If not, can you please give more details, with the full error traceback?
