### ISSUE TITLE
[BUG] `manim-slides present` and `wizard` immediately crash

### ISSUE THREAD

**Issue by johanohly** [jeertmans/manim-slides#435]
### Description

I am probably doing something very stupid, but I cannot figure out what I am doing wrong to get this result. 
See the screenshot. 

### Version

5.1.7

### Platform

Windows

### Screenshots

https://github.com/jeertmans/manim-slides/assets/64006750/470196d8-a8a3-478e-bbdd-26014509b1c6

**Comment by JohnnyJTH** [comment]
Potentially relevant info:
I just tried running `manim-slides wizard` but that command also failed. 

<details>
<summary>Traceback</summary>
![image](https://github.com/jeertmans/manim-slides/assets/64006750/e52d3dec-28aa-4aa1-9641-a64f36a413d2)
</details>

**Comment by jeertmans** [comment]
Hello! I guess you are on Windows and using a virtualenv (which is nice!)?

If so, can you show the output of `pip freeze`?

Also, can you show the top of the error message in your video? I recognize this error, but I cannot remember where I saw it...

**Comment by JohnnyJTH** [comment]
Yes! I am using python 3.12.3 and its' standard `venv` module for the virtualenv. 

The error message consists of this block of text repeated over and over:
![image](https://github.com/jeertmans/manim-slides/assets/64006750/333ca100-0a2c-44ff-89d2-26a11d7ed5f8)

`pip freeze`:
![image](https://github.com/jeertmans/manim-slides/assets/64006750/4155d4f3-2bf2-42f0-b6a4-d881b1fb269c)

**Comment by jeertmans** [comment]
Thanks! Did you try with Python 3.11?

Just to check if Python 3.12 is the issue

**Comment by JohnnyJTH** [comment]
Python 3.11 gives me the same error

**Comment by jeertmans** [comment]
Ok, so I also encountered this issue with my PR #377.

Can you try presenting with `manim-slides present [SCENE]... --hide-info-window`?

**Comment by JohnnyJTH** [comment]
That fixes it.

**Comment by jeertmans** [comment]
Thanks for the update @JohnnyJTH, hopefully I will find a better fix and push it to #377 :-)

Does `manim-slides wizard` still crash?

**Comment by JohnnyJTH** [comment]
> Thanks for the update @JohnnyJTH, hopefully I will find a better fix and push it to #377 :-)
> 
> Does `manim-slides wizard` still crash?

Sorry for not replying earlier, `manim-slides wizard` works with 3.11 at least

**Comment by jeertmans** [comment]
No issue, thanks for the reply @JohnnyJTH!

**Comment by jeertmans** [comment]
Closing, see https://github.com/jeertmans/manim-slides/pull/377#issuecomment-2331371543.
