### ISSUE TITLE
[BUG] manim-slides is not recognized

### ISSUE THREAD

**Issue by AndrewDTR** [jeertmans/manim-slides#44]
### Description

"manim-slides" command not working after pip + git install. I'm probably making some silly mistake but I can't seem to figure out why it's not binding in the console. Tried restarting + adding to PATH but still nothing

### Version

4.1.1

### Platform

Windows

### Screenshots

![image](https://user-images.githubusercontent.com/74398819/194459555-7f305d2e-e76c-4481-99dc-fc27e8e7d69e.png)

**Comment by AndrewDTR** [comment]
Yeah, if I link to the actual .exe file it seems to work fine, just not through the PATH. Even when I add it directly under `manim-slides`. Rerunning pip install shows:
```  WARNING: The script manim-slides.exe is installed in 'C:\Users\Draw\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.```

**Comment by jeertmans** [comment]
Ok so that’s what I thought :)
Can you consider reading this blog post and trying all possible solutions ?
https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/

If the Scripts dir is correctly placed in PATH, then this should work.
