### ISSUE TITLE
[BUG] Manim-Slides cannot present the slides

### ISSUE THREAD

**Issue by almahmoud-phys** [jeertmans/manim-slides#448]
### Please explain the issue you're experiencing (with as much detail as possible):

I get this error message:

### Command
`manim-slides BasicExample`

### Error
 manim-slides BasicExample
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3ABA04C0] get_buffer() failed
[h264 @ 0000021F3ABA04C0] thread_get_buffer() failed
[h264 @ 0000021F3ABA04C0] decode_slice_header error
[h264 @ 0000021F3ABA04C0] no frame!
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3ABA10C0] get_buffer() failed
[h264 @ 0000021F3ABA10C0] thread_get_buffer() failed
[h264 @ 0000021F3ABA10C0] decode_slice_header error
[h264 @ 0000021F3ABA10C0] no frame!
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3AB9F0C0] get_buffer() failed
[h264 @ 0000021F3AB9F0C0] thread_get_buffer() failed
[h264 @ 0000021F3AB9F0C0] decode_slice_header error
[h264 @ 0000021F3AB9F0C0] no frame!
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3AB9F8C0] get_buffer() failed
[h264 @ 0000021F3AB9F8C0] thread_get_buffer() failed
[h264 @ 0000021F3AB9F8C0] decode_slice_header error
[h264 @ 0000021F3AB9F8C0] no frame!
[AVHWFramesContext @ 0000021F5F0A3E80] Static surface pool size exceeded.
[h264 @ 0000021F3ABA5CC0] get_buffer() failed
[h264 @ 0000021F3ABA5CC0] thread_get_buffer() failed
[h264 @ 0000021F3ABA5CC0] decode_slice_header error
[h264 @ 0000021F3ABA5CC0] no frame!
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3ABA50C0] get_buffer() failed
[h264 @ 0000021F3ABA50C0] thread_get_buffer() failed
[h264 @ 0000021F3ABA50C0] decode_slice_header error
[h264 @ 0000021F3ABA50C0] no frame!
[AVHWFramesContext @ 0000021F5F0A3E80] Static surface pool size exceeded.
[h264 @ 0000021F3ABA60C0] get_buffer() failed
[h264 @ 0000021F3ABA60C0] thread_get_buffer() failed
[h264 @ 0000021F3ABA60C0] decode_slice_header error
[AVHWFramesContext @ 0000021F3A87BF40] Static surface pool size exceeded.
[h264 @ 0000021F3AB9FCC0] get_buffer() failed
[h264 @ 0000021F3AB9FCC0] thread_get_buffer() failed
[h264 @ 0000021F3AB9FCC0] decode_slice_header error
[h264 @ 0000021F3AB9FCC0] no frame!
[h264 @ 0000021F3ABA60C0] no frame!
[h264 @ 0000021F3ABA20C0] reference picture missing during reorder
[h264 @ 0000021F3ABA20C0] reference picture missing during reorder
[h264 @ 0000021F3ABA20C0] Missing reference picture, default is 65592
[h264 @ 0000021F3ABA20C0] Missing reference picture, default is 65592
[h264 @ 0000021F3ABA40C0] mmco: unref short failure
[h264 @ 0000021F3ABA64C0] reference picture missing during reorder
[h264 @ 0000021F3ABA64C0] Missing reference picture, default is 65604
[h264 @ 0000021F3ABA24C0] mmco: unref short failure
    failed to get textures for frame; format: 172 textureConverter null

### Python code
```
from manim import *  # or: from manimlib import *
from manim_slides import Slide


class BasicExample(Slide):
    def construct(self):
        circle = Circle(radius=3, color=BLUE)
        dot = Dot()

        self.play(GrowFromCenter(circle))
        self.next_slide()  # Waits user to press continue to go to the next slide

        self.next_slide(loop=True)  # Start loop
        self.play(MoveAlongPath(dot, circle), run_time=2, rate_func=linear)
        self.next_slide()  # This will start a new non-looping slide

        self.play(dot.animate.move_to(ORIGIN))
```

### Manim version:
> manim --version

(process:2824): GLib-GIO-WARNING **: 00:57:07.758: Unexpectedly, UWP app `38526MediaLife.ZipPlus_2.0.4.0_x86__1crh1k73ty8mg' (AUMId `38526MediaLife.ZipPlus_1crh1k73ty8mg!ZipExtractor') supports 89 extensions but has no verbs
Manim Community v0.18.1

> manimcce --version
Manim Community v0.18.1

### ffmpeg:
1. > ffmpeg --version
ffmpeg version 7.0.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint      
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Unrecognized option '-version'.
Error splitting the argument list: Option not found

2. > pip show ffmpeg
Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: c:\users\-----\onedrive - ugent\python projects\manimprojects\venv\lib\site-packages
Requires:
Required-by:

**Comment by jeertmans** [comment]
Hello! I think this issue might be similar to another one. Can you try the fix I mentioned in https://github.com/jeertmans/manim-slides/issues/402#issuecomment-2042776337?

Long story short, the support on Windows platforms does not seem consistent over all Python and Qt versions…

**Comment by almahmoud-phys** [comment]
Thanks Jérome, it is working now

**Comment by TommyLITommy** [comment]
Hi  Jérome, I saw the examples on your manim-slides website, so how did you embeded the slides on the web?

**Comment by jeertmans** [comment]
> Hi Jérome, I saw the examples on your manim-slides website, so how did you embeded the slides on the web?

Hi @TommyLITommy, thanks for your question! However, this is not an appropriate place to ask questions, especially as it has nothing to do with this issue. I have opened (and answered) a discussion for this: https://github.com/jeertmans/manim-slides/discussions/487.
