### ISSUE TITLE
[BUG] Next/Previous Slide does not work with left/right keys

### ISSUE THREAD

**Issue by WUCHENG98** [jeertmans/manim-slides#45]
### Description

When I tried to use the provided examples, I can't use the left/right keys to jump to the next/previous slide.

### Version

manim-slides, version 4.1.1

### Platform

macOS, M1 chip

**Comment by WUCHENG98** [comment]
I found the bug! The key id for macOS is wrong is should be:
``RIGHT_ARROW_KEY_CODE = 63235
    LEFT_ARROW_KEY_CODE = 63234``

**Comment by jeertmans** [comment]
Hi @WUCHENG98, many thanks for raising this issue!

Do you want to propose a PR with your solution?

**Comment by jeertmans** [comment]
FYI @WUCHENG98, you can implement your solution by adding an `elif` clause to https://github.com/jeertmans/manim-slides/blob/501813483c1d17d74c59d5f801de7c298b31066c/manim_slides/defaults.py#L9-L14

macOS platform system is called `Darwin` :)

**Comment by WUCHENG98** [comment]
Thanks! I submitted the PR!
