### ISSUE TITLE
[BUG] <import Slide>

### ISSUE THREAD

**Issue by FMacielzx** [jeertmans/manim-slides#473]
### Terms

- [X] Checked the [existing issues](https://github.com/jeertmans/manim-slides/issues?q=is%3Aissue+label%3Adocumentation+) and [discussions](https://github.com/jeertmans/manim-slides/discussions) to see if my issue had not already been reported;
- [X] Read the [installation instructions](https://manim-slides.eertmans.be/latest/installation.html);
- [ ] Created a virtual environment in which I can reproduce my bug;

### Describe the issue

My Vs Code don't recognize the import Slide and I cannot run my slide 

### Command

import Slide

### Issue Type

Visual bug when presenting (`manim-slides present`)

### Python version

Python 3.12.6

### Python environment

```shell
rom manim_slides import Slide #Here
from manim import *
class MySlide (Slide):
      def construct (self):
          circle = Circle(radius = 3, color = BLUE)
          dot = Dot().move_to(circle.get_right())

          self.play(Create(circle), GrowFromCenter(dot))
          self.stop() #Espera o clique para passar para o próximo slide 

          self.play(MoveAlongPath(dot, circle), run_time=2, rate_func= linear)
          self.stop()

          self.play(dot.animate.move_to(ORIGIN))
          self.stop() #Espera o clique para passar para o próximo slide
          self.wait()

      def stop(self):
          self.wait(0.3)
          self.pause()
```

### What is your platform?

Windows

**Comment by jeertmans** [comment]
Hello @FMacielzx, thank you for reporting your issue.

However, I will need more context to understand what's not working...

First, you did not tick the box

> - [ ] Created a virtual environment in which I can reproduce my bug;

But it is very important to have a correctly working Python environment, and it is very frequent that errors emerge from not having a correct setup. Please follow the installation instruction to this end.

Second, you mention a visual bug, then please include a screenshot of it! I cannot know what you expected and what you got instead.

If the error is just that Visual Studio code does not recognize imports from `manim_slides`, it is very likely that it isn't using the same Python environment as the one you installed Manim Slides in.

If you cannot run the command, please provide the output :-)

**Comment by jeertmans** [comment]
I am closing this as the author is not giving any response, please feel free to re-open if that is still an issue.

**Comment by FMacielzx** [comment]
Thank you for replying to me, but I did fix my bug after reading some pages
of manim slides documentation. If I need any help I'll contact you 🙏

Em qua., 25 de set. de 2024 às 04:14, Jérome Eertmans <
***@***.***> escreveu:
