### ISSUE TITLE
[BUG] qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by Haetham96** [jeertmans/manim-slides#478]
### Terms

- [X] Checked the [existing issues](https://github.com/jeertmans/manim-slides/issues?q=is%3Aissue+label%3Abug+) and [discussions](https://github.com/jeertmans/manim-slides/discussions) to see if my issue had not already been reported;
- [X] Checked the [frequently qsked questions]](https://manim-slides.eertmans.be/latest/faq.html);
- [X] Read the [installation instructions](https://manim-slides.eertmans.be/latest/installation.html);
- [X] Created a virtual environment in which I can reproduce my bug;

### Describe the issue

Hello, 
I am unable to run manim-slides, thank you in advance for your help!

I am on Ubuntu 22.04.5 LTS and my python version is 3.10.12. 

I created a python virtual enviornement in which I installed manim with 
``` pip3 install manim ```, and it works fine.

Then, I installed manim-slides with 
``` pip install manim-slides[pyside6] ```.

When running an example with 
``` manim example.py BasicExample ```, and then 
``` manim-slides BasicExample ```, I get the following error 

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimalegl, wayland, vkkhrdisplay, vnc, offscreen, linuxfb, minimal, xcb, wayland-egl, eglfs.

Aborted
```

### Command

manim-slides BasicExample

### Issue Type

Installation issue

### Python version

Python 3.10.12

### Python environment

```shell
Error: File slides/checkhealth.json does not exist, check the scene name and make sure to use Slide as your scene base class
```

### What is your platform?

Linux

### Manim Slides Python code

```python
from manim import *  # or: from manimlib import *
from manim_slides import Slide

class BasicExample(Slide):
    def construct(self):
        circle = Circle(radius=3, color=BLUE)
        dot = Dot()

        self.play(GrowFromCenter(circle))
        self.next_slide()  # Waits user to press continue to go to the next slide

        self.next_slide(loop=True)  # Start loop
        self.play(MoveAlongPath(dot, circle), run_time=2, rate_func=linear)
        self.next_slide()  # This will start a new non-looping slide

        self.play(dot.animate.move_to(ORIGIN))
```

**Comment by jeertmans** [comment]
Hi @Haetham96, thanks you for reporting this issue!

Are you using Wayland?

Also, can you try this if this fixes your problem? https://github.com/NVlabs/instant-ngp/discussions/300#discussioncomment-3985753

**Comment by Haetham96** [comment]
No I am not using Wayland.
I tried the proposed solution, still gives the same error.

**Comment by jeertmans** [comment]
Can try installing Manim Slides only (but with pyside6-full extra) from the main branch?

**Comment by jeertmans** [comment]
Could you check [this thread](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/2) to see if that can help? Also, run the application with `QT_DEBUG_PLUGINS` set to `1`, e.g.:

```bash
QT_DEBUG_PLUGINS=1 manim-slides present BasicExample
```

**Comment by Haetham96** [comment]
It works !! 
Fixed by installing 'libxcb-cursor0' from
```http://archive.ubuntu.com/ubuntu/pool/universe/x/xcb-util-cursor/libxcb-cursor0_0.1.1-4ubuntu1_amd64.deb```

Thank you very much !!

**Comment by jeertmans** [comment]
Happy it solved your issue :-)
