### ISSUE TITLE
[FEATURE] Add an option/flag to hide mouse cursor

### ISSUE THREAD

**Issue by Azercoco** [jeertmans/manim-slides#48]
### Description

I am using manim-slides for live presentation and there does not seem to be an option to hide the cursor and I have to put it in a screen corner so it does not hinder the presentation which is annoying.

### Additional information

I'm using version 4.1.1 on Windows 11.

**Comment by jeertmans** [comment]
Hi @Azercoco, thank you for suggesting this new feature!

Indeed, hiding the mouse pointer would be very convenient, especially for single screen presentation (I usually hide my mouse on the secondary screen).

However, this does not seem to be supported by OpenCV, which Manim Slides is using for video presentation.

An alternative would be to use PyQT5, or Tkinter, for presenting videos, but that would require quite a lot a work.

I don't have time for that now, but if you want to work on that, feel free to do so! 

Some links:
- [pyqt5 video widget](https://pythonprogramminglanguage.com/pyqt5-video-widget/)
- [disable mouse qith pyqt5](https://stackoverflow.com/questions/54429657/disable-mouse-pointer-in-qgraphicsview)
- [cannot hide mouse with opencv](https://stackoverflow.com/questions/18761133/hide-mouse-cursor-in-opencv)
- [qt video player using opencv](https://github.com/kaka-lin/qt-video-player)
- [qt with opencv](https://gist.github.com/docPhil99/ca4da12c9d6f29b9cea137b617c7b8b1)
