### ISSUE TITLE
[BUG] Blank web page when converting multiple slides into HTML

### ISSUE THREAD

**Issue by simanglam** [jeertmans/manim-slides#496]
### Terms

- [X] Checked the [existing issues](https://github.com/jeertmans/manim-slides/issues?q=is%3Aissue+label%3Abug+) and [discussions](https://github.com/jeertmans/manim-slides/discussions) to see if my issue had not already been reported;
- [X] Checked the [frequently asked questions]](https://manim-slides.eertmans.be/latest/faq.html);
- [X] Read the [installation instructions](https://manim-slides.eertmans.be/latest/installation.html);
- [X] Created a virtual environment in which I can reproduce my bug;

### Describe the issue

Hi,

I was trying to make a presentation with manim-slides, and I divid my whole presentation into few small scenes for faster rendering. When I convert all of my slides into HTML, the HTML page is blank, it doesn't play any animation.

I dig into HTML file and asset directory a little and try to find the reason. Here is my discover, when manin-slides convert multiple slides into html, it add prefix to animation file in asset directory to prevent filename collision (as #428 mentioned) but doesn't add the prefix in HTML's reference to the file.

PS, English is not my native language; please excuse typing errors.

### Command

manim-slides render mwe.py MWE1 && manim-slides render mwe.py MWE2 && manim-slides convert MWE1 MWE2 index.html

### Issue Type

Bug when presenting with HTML/PowerPoint/... format (`manim-slides convert`)

### Python version

Python 3.11.10

### Python environment

```shell
Manim Slides version: 5.1.9
Python executable: /Users/simanglam/Desktop/uni/slides/manim/venv/bin/python
Manim bindings:
        manim (version: 0.18.1)
        manimgl not found
Qt API: pyside6 (version: 6.8.0)
```

### What is your platform?

macOS

### Manim Slides Python code

```python
from manim import *
from manim_slides.slide import Slide

class MWE1(Slide):
    def construct(self):
        dot = Dot().set_color(BLUE)
        self.play(FadeIn(dot))
        self.next_slide()
        
        
class MWE2(Slide):
    def construct(self):
        dot = Dot().set_color(YELLOW)
        self.play(Create(dot))
```

**Comment by jeertmans** [comment]
Hi @simanglam, thanks for reporting this bug (and solving it in another PR)!
