### ISSUE TITLE
[FEATURE] toggle mouse display with key

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#51]
### Description

Currently, it is not possible to hide or show the mouse during the presentation.

This would be a nice feature to add.

### Additional information

A key, e.g. `HIDE_MOUSE: Key = Key(ids[Qt.Key_H], name="HIDE / SHOW MOUSE")` shoud be created in `manim_slides/config.py`.

Then, the `App.keyPressEvent` method in `manim_slides/config.py` should be modified to listen to `config.HIDE_MOUSE.match(key)` and toggle on / off the blank key.

Note that the `config` argument must, therefore, also be saved in `App` and that some kind of state must be kept about whether the mouse is hidden or not.

**Comment by MikeGillotti** [comment]
Hello, I'm interested in working on this task.

**Comment by jeertmans** [comment]
Hi @MikeGillotti, glad to hear that! :D 

Feel free to start working on this, and propose a Pull Request once you feel ready for a review :)

**Comment by jeertmans** [comment]
Closed with #56
