### ISSUE TITLE
[FEATURE] setting background color with `aspect-ratio=keep`

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#52]
### Description

When using `aspect-ratio=keep`, the background color is white.
However, this might look weird on presentations with, e.g., black background color.

I propose to add a background color option in the CLI, that defaults to black.

### Screenshots

The goal is to change the color of the borders.

![image](https://user-images.githubusercontent.com/27275099/196654760-89d619f6-d518-47f4-8342-84ba76260beb.png)

Example of desired output with `background-color=black`:

![image](https://user-images.githubusercontent.com/27275099/196654990-3e721cf4-c944-4d41-9b70-cbe9ef080647.png)

### Additional information

All the changes should occur in `manim_slides/present.py`.

First, create a new keyword argument to `App.__init__` called
```python
background_color: str = "black"
```

Then, after `self.label = QLabel(self)`, write
```python
self.label.setStyleSheet(f"background-color: {background_color}")
```

After that, you need to add a new argument to the CLI (see `@click.option`) and pass it to the `App` instance.

**Comment by Anmol-Ghadia** [comment]
Hi, can I be assigned to this issue?

**Comment by jeertmans** [comment]
Hi, of course @Anmol-Ghadia!
I am glad you are interested in helping this project :D

**Comment by jeertmans** [comment]
Hi @Anmol-Ghadia, still working on this?

**Comment by Anmol-Ghadia** [comment]
Hi, I am so sorry for taking so long. If possible can you give me few more days to try it?

**Comment by jeertmans** [comment]
Yes of course @Anmol-Ghadia!

**Comment by Anmol-Ghadia** [comment]
Hi, I am really sorry. I will not be able to complete this feature. You can remove me from assigned. Thank you for your patience and understanding.

**Comment by jeertmans** [comment]
No problem @Anmol-Ghadia ;)
I’ll probably work on this and create a PR. If you are interested, I can tag you so that you see how you could have done that?

**Comment by jeertmans** [comment]
Hi @Anmol-Ghadia, you can check [#60](https://github.com/jeertmans/manim-slides/pull/60/files) to see what I was roughly expecting with this issue ;-)

If you want to try adding another feature, please feel free to propose!
