### ISSUE TITLE
zsh: command not found: manim-slides

### ISSUE THREAD

**Issue by pgvanhoven** [jeertmans/manim-slides#55]
The installation of manim-slides, via pip3, worked totally fine. Initially compiling the example scene worked fine as well. However, running `manim-slides Example` doesn't work, and returns zsh: command not found: manim-slides. How do I fix this?

**Comment by jeertmans** [comment]
Hi @pgvanhoven, that’s probably the same problem as in #44. You most likely do not have Python scripts installed in a directory located in PATH. 

Can you uninstall, then install Manim Slides and report the output here?
