### ISSUE TITLE
[FEATURE] Official Python3.11 support

### ISSUE THREAD

**Issue by tdadela** [jeertmans/manim-slides#71]
### Description

Python 3.11 was released in October.
I think, it is good idea to add official support.

Action needed:
1. add test builds for Python3.11,
2. add Python3.11 README badge.

**Comment by jeertmans** [comment]
Hi @tdadela, indeed that’s a good idea!
Do you want to take care of this? Otherwise I will do it when I have time :)

Thanks for raising this issue!

**Comment by tdadela** [comment]
> Do you want to take care of this? 

Yes
But I'm not sure if I will be doing it next weekend / next month.

**Comment by jeertmans** [comment]
Hi @tdadela, sorry to finally take on this one, but I wanted to move on next features for Manim Slides, and I prefer not to stall issues / PRs for too long ;-)

I hope you don't mind!
