### ISSUE TITLE
Qt Plugin Cannot be Initialized Error - Anaconda

### ISSUE THREAD

**Issue by lucaslibshutz** [jeertmans/manim-slides#96]
### Please explain the issue you're experiencing (with as much detail as possible):

Hello, 
I've unfortunately been getting the same error when trying to run manim-slides of a scene. The error looks like below:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/82786575/206819523-f8184618-f208-4c93-966d-7e593ecf761b.png">
I've tried to uninstall my conda distribution, reset my entire Windows PC, and try and install pyqt5-tools separately, yet none have worked. Is this a bug or is there something that I am missing?

Thank you!

P.S. - The files used in this bug were pulled straight from the main page of the repository.

**Comment by jeertmans** [comment]
Hi @lucaslibshutz, thanks for raising this issue :)

This bug is weird, and Manim Slides should work fine just in one pip install.

Can you create a virtual environment, pip install manim and manim-slides, and copy the output of the installation process? Then, run manim and then manim-slides to see if they work?

Thanks in advance!

Ps: Manim Slides uses PySide6, not PyQt5, so I am not sure about this pyqt5-tools you installed.

**Comment by lucaslibshutz** [comment]
Hi @jeertmans ,

I made a new Conda environment, installed `manim` and `manim-slides` from scratch, and it worked like a charm! However, I think I was able to find the main problem.

Whenever the user installs the base conda environment, it automatically has `qt` packages installed, while a fresh environment does not. See the below, where the `base` environment has both `manim` and `manim-slides` installed along with base pip packages, and the `sTest` environment, with both `manim` and `manim-slides` installed:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/82786575/206882179-8bb53cdc-7278-414c-a66e-27f75dae1b61.png">

Therefore, when I try to use manim-slides with both environments, the below happens (the blank line at the end indicates that `manim-slides` worked and exited as expected:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/82786575/206882238-dec00d33-29f7-4567-b74b-ed346be4927d.png">
The `sTest` environment works without a hitch, while the `base` environment (after a base Conda install) has the same error as before. 

Maybe there is a way for any user's base Conda environment to default to the `PySide6` Qt installation, rather than that of `QtPy`? What do you think?

Thanks for your help!

**Comment by jeertmans** [comment]
Hi, I am glad you found a way around!

After digging a bit, it seems that creating a virtual env. is the only solution, see this comment by *CristianMaureira* from this [thread](https://forum.qt.io/topic/135824/how-to-make-run-pyside6-in-current-anaconda-installation-conda-4-12-0/4):
> The problematic area here is that conda is really good to resolve extra dependencies for Python packages, like for example when you try to use the Python OpenGL bindings, but that means they require to have the proper configuration of Qt in their packages. That being said, modules like matplotlib might install a 'qt.conf' file that modify how Qt will work in your environment, which is problematic, because if you have PySide first, then PyQt might not work, and the other way around.

> Officially, there is no conda packages for PySide6 provided by the Qt Project (nor the Qt company), and we only provide the ones on PyPi that you can get with pip install pyside6.

> So why is that an issue? The wheels you install with pip include Qt binaries, and what if you already have Qt installed in your conda environment? then there will be a problem with all the configurations. This is the main reason on why we encourage users to use a vanilla Python interpreter, create a virtual environment and install pyside and all the other dependencies there.

> If you really cannot do that, I'd recommend you to create another 'conda enviroment' and "try" to install there PySide6 and give it a try.

I am closing this as completed, as you found a solution to your problem :)

Many thanks for you interest in this project!

**Comment by shivams** [comment]
As a side-note, this error also shows up on Linux/Ubuntu when using pip. The exact error that shows up is this:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, wayland-egl, vnc, offscreen, linuxfb, eglfs, xcb, vkkhrdisplay, minimal, minimalegl.

[1]    1398378 IOT instruction (core dumped)  manim-slides BasicExample
```

The resolution was to install the following packages:

```shell
sudo apt install libxcb-cursor0 libxcb-cursor-dev 
```

**Comment by jeertmans** [comment]
Thanks @shivams :-) This was actually already documented in the [v4.14 release notes](https://github.com/jeertmans/manim-slides/releases/tag/v4.14.0).
